Vagrant.configure("2") do |config|
  
  config.vm.define "control" do |ctl|
    ctl.vm.box = "ubuntu/trusty64"
    ctl.vm.hostname = "ubuntu-control"
    ctl.vm.network "private_network", ip: "192.168.57.2"
    ctl.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
    end
    ctl.vm.provision "file", source: "ansible_remote", destination: "$HOME/ansible"
    ctl.vm.provision "shell", path: "ansible.sh"
  end

  config.vm.define "webserver01" do |web01|
    web01.vm.box = "vb2016"
    web01.vm.hostname = "win-web-01"
    web01.vm.communicator = "winrm"
    web01.winrm.username = "vagrant"
    web01.winrm.password = "vagrant"
    web01.vm.network "private_network", ip: "192.168.57.3"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
  end

  config.vm.define "webserver02" do |web02|
    web02.vm.box = "vb2016"
    web02.vm.hostname = "win-web-02"
    web02.vm.communicator = "winrm"
    web02.winrm.username = "vagrant"
    web02.winrm.password = "vagrant"
    web02.vm.network "private_network", ip: "192.168.57.4"
    web02.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
  end
end

